INSERT INTO category (name) VALUES
('Electronics'),
('Books'),
('Clothing'),
('Home & Kitchen'),
('Sports & Outdoors'),
('Beauty & Personal Care'),
('Toys & Games'),
('Automotive'),
('Grocery'),
('Health & Wellness'),
('Wearable Tech'),
('Gaming'),
('Furniture'),
('Outdoor Gear'),
('Pet Supplies'),
('Smart Home'),
('Appliances'),
('Tools & Home Improvement'),
('Health Devices'),
('Office Supplies');
