INSERT INTO country (code, name, image_url) VALUES
('AF', 'Afghanistan', 'https://flagsapi.com/AF/flat/64.png'),
('AL', 'Albania', 'https://flagsapi.com/AL/flat/64.png'),
('DZ', 'Algeria', 'https://flagsapi.com/DZ/flat/64.png'),
('AD', 'Andorra', 'https://flagsapi.com/AD/flat/64.png'),
('AO', 'Angola', 'https://flagsapi.com/AO/flat/64.png'),
('AR', 'Argentina', 'https://flagsapi.com/AR/flat/64.png'),
('AM', 'Armenia', 'https://flagsapi.com/AM/flat/64.png'),
('AU', 'Australia', 'https://flagsapi.com/AU/flat/64.png'),
('AT', 'Austria', 'https://flagsapi.com/AT/flat/64.png'),
('AZ', 'Azerbaijan', 'https://flagsapi.com/AZ/flat/64.png'),
('BS', 'Bahamas', 'https://flagsapi.com/BS/flat/64.png'),
('BH', 'Bahrain', 'https://flagsapi.com/BH/flat/64.png'),
('BD', 'Bangladesh', 'https://flagsapi.com/BD/flat/64.png'),
('BB', 'Barbados', 'https://flagsapi.com/BB/flat/64.png'),
('BY', 'Belarus', 'https://flagsapi.com/BY/flat/64.png'),
('BE', 'Belgium', 'https://flagsapi.com/BE/flat/64.png'),
('BZ', 'Belize', 'https://flagsapi.com/BZ/flat/64.png'),
('BJ', 'Benin', 'https://flagsapi.com/BJ/flat/64.png'),
('BT', 'Bhutan', 'https://flagsapi.com/BT/flat/64.png'),
('BO', 'Bolivia', 'https://flagsapi.com/BO/flat/64.png'),
('BA', 'Bosnia and Herzegovina', 'https://flagsapi.com/BA/flat/64.png'),
('BW', 'Botswana', 'https://flagsapi.com/BW/flat/64.png'),
('BR', 'Brazil', 'https://flagsapi.com/BR/flat/64.png'),
('BN', 'Brunei', 'https://flagsapi.com/BN/flat/64.png'),
('BG', 'Bulgaria', 'https://flagsapi.com/BG/flat/64.png'),
('BF', 'Burkina Faso', 'https://flagsapi.com/BF/flat/64.png'),
('BI', 'Burundi', 'https://flagsapi.com/BI/flat/64.png'),
('CV', 'Cabo Verde', 'https://flagsapi.com/CV/flat/64.png'),
('KH', 'Cambodia', 'https://flagsapi.com/KH/flat/64.png'),
('CM', 'Cameroon', 'https://flagsapi.com/CM/flat/64.png'),
('CA', 'Canada', 'https://flagsapi.com/CA/flat/64.png'),
('CF', 'Central African Republic', 'https://flagsapi.com/CF/flat/64.png'),
('TD', 'Chad', 'https://flagsapi.com/TD/flat/64.png'),
('CL', 'Chile', 'https://flagsapi.com/CL/flat/64.png'),
('CN', 'China', 'https://flagsapi.com/CN/flat/64.png'),
('CO', 'Colombia', 'https://flagsapi.com/CO/flat/64.png'),
('KM', 'Comoros', 'https://flagsapi.com/KM/flat/64.png'),
('CG', 'Congo', 'https://flagsapi.com/CG/flat/64.png'),
('CD', 'Congo (DRC)', 'https://flagsapi.com/CD/flat/64.png'),
('CR', 'Costa Rica', 'https://flagsapi.com/CR/flat/64.png'),
('HR', 'Croatia', 'https://flagsapi.com/HR/flat/64.png'),
('CU', 'Cuba', 'https://flagsapi.com/CU/flat/64.png'),
('CY', 'Cyprus', 'https://flagsapi.com/CY/flat/64.png'),
('CZ', 'Czech Republic', 'https://flagsapi.com/CZ/flat/64.png'),
('DK', 'Denmark', 'https://flagsapi.com/DK/flat/64.png'),
('DJ', 'Djibouti', 'https://flagsapi.com/DJ/flat/64.png'),
('DM', 'Dominica', 'https://flagsapi.com/DM/flat/64.png'),
('DO', 'Dominican Republic', 'https://flagsapi.com/DO/flat/64.png'),
('EC', 'Ecuador', 'https://flagsapi.com/EC/flat/64.png'),
('EG', 'Egypt', 'https://flagsapi.com/EG/flat/64.png'),
('SV', 'El Salvador', 'https://flagsapi.com/SV/flat/64.png'),
('GQ', 'Equatorial Guinea', 'https://flagsapi.com/GQ/flat/64.png'),
('ER', 'Eritrea', 'https://flagsapi.com/ER/flat/64.png'),
('EE', 'Estonia', 'https://flagsapi.com/EE/flat/64.png'),
('SZ', 'Eswatini', 'https://flagsapi.com/SZ/flat/64.png'),
('ET', 'Ethiopia', 'https://flagsapi.com/ET/flat/64.png'),
('FJ', 'Fiji', 'https://flagsapi.com/FJ/flat/64.png'),
('FI', 'Finland', 'https://flagsapi.com/FI/flat/64.png'),
('FR', 'France', 'https://flagsapi.com/FR/flat/64.png'),
('GA', 'Gabon', 'https://flagsapi.com/GA/flat/64.png'),
('GM', 'Gambia', 'https://flagsapi.com/GM/flat/64.png'),
('GE', 'Georgia', 'https://flagsapi.com/GE/flat/64.png'),
('DE', 'Germany', 'https://flagsapi.com/DE/flat/64.png'),
('GH', 'Ghana', 'https://flagsapi.com/GH/flat/64.png'),
('GR', 'Greece', 'https://flagsapi.com/GR/flat/64.png'),
('GD', 'Grenada', 'https://flagsapi.com/GD/flat/64.png'),
('GT', 'Guatemala', 'https://flagsapi.com/GT/flat/64.png'),
('GN', 'Guinea', 'https://flagsapi.com/GN/flat/64.png'),
('GW', 'Guinea-Bissau', 'https://flagsapi.com/GW/flat/64.png'),
('GY', 'Guyana', 'https://flagsapi.com/GY/flat/64.png'),
('HT', 'Haiti', 'https://flagsapi.com/HT/flat/64.png'),
('HN', 'Honduras', 'https://flagsapi.com/HN/flat/64.png'),
('HU', 'Hungary', 'https://flagsapi.com/HU/flat/64.png'),
('IS', 'Iceland', 'https://flagsapi.com/IS/flat/64.png'),
('IN', 'India', 'https://flagsapi.com/IN/flat/64.png'),
('ID', 'Indonesia', 'https://flagsapi.com/ID/flat/64.png'),
('IR', 'Iran', 'https://flagsapi.com/IR/flat/64.png'),
('IQ', 'Iraq', 'https://flagsapi.com/IQ/flat/64.png'),
('IE', 'Ireland', 'https://flagsapi.com/IE/flat/64.png'),
('IL', 'Israel', 'https://flagsapi.com/IL/flat/64.png'),
('IT', 'Italy', 'https://flagsapi.com/IT/flat/64.png'),
('JM', 'Jamaica', 'https://flagsapi.com/JM/flat/64.png'),
('JP', 'Japan', 'https://flagsapi.com/JP/flat/64.png'),
('JO', 'Jordan', 'https://flagsapi.com/JO/flat/64.png'),
('KZ', 'Kazakhstan', 'https://flagsapi.com/KZ/flat/64.png'),
('KE', 'Kenya', 'https://flagsapi.com/KE/flat/64.png'),
('KI', 'Kiribati', 'https://flagsapi.com/KI/flat/64.png'),
('KP', 'North Korea', 'https://flagsapi.com/KP/flat/64.png'),
('KR', 'South Korea', 'https://flagsapi.com/KR/flat/64.png'),
('KW', 'Kuwait', 'https://flagsapi.com/KW/flat/64.png'),
('KG', 'Kyrgyzstan', 'https://flagsapi.com/KG/flat/64.png'),
('LA', 'Laos', 'https://flagsapi.com/LA/flat/64.png'),
('LV', 'Latvia', 'https://flagsapi.com/LV/flat/64.png'),
('LB', 'Lebanon', 'https://flagsapi.com/LB/flat/64.png'),
('LS', 'Lesotho', 'https://flagsapi.com/LS/flat/64.png'),
('LR', 'Liberia', 'https://flagsapi.com/LR/flat/64.png'),
('LY', 'Libya', 'https://flagsapi.com/LY/flat/64.png'),
('LI', 'Liechtenstein', 'https://flagsapi.com/LI/flat/64.png'),
('LT', 'Lithuania', 'https://flagsapi.com/LT/flat/64.png'),
('LU', 'Luxembourg', 'https://flagsapi.com/LU/flat/64.png'),
('MG', 'Madagascar', 'https://flagsapi.com/MG/flat/64.png'),
('MW', 'Malawi', 'https://flagsapi.com/MW/flat/64.png'),
('MY', 'Malaysia', 'https://flagsapi.com/MY/flat/64.png'),
('MV', 'Maldives', 'https://flagsapi.com/MV/flat/64.png'),
('ML', 'Mali', 'https://flagsapi.com/ML/flat/64.png'),
('MT', 'Malta', 'https://flagsapi.com/MT/flat/64.png'),
('MH', 'Marshall Islands', 'https://flagsapi.com/MH/flat/64.png'),
('MR', 'Mauritania', 'https://flagsapi.com/MR/flat/64.png'),
('MU', 'Mauritius', 'https://flagsapi.com/MU/flat/64.png'),
('MX', 'Mexico', 'https://flagsapi.com/MX/flat/64.png'),
('FM', 'Micronesia', 'https://flagsapi.com/FM/flat/64.png'),
('MD', 'Moldova', 'https://flagsapi.com/MD/flat/64.png'),
('MC', 'Monaco', 'https://flagsapi.com/MC/flat/64.png'),
('MN', 'Mongolia', 'https://flagsapi.com/MN/flat/64.png'),
('ME', 'Montenegro', 'https://flagsapi.com/ME/flat/64.png'),
('MA', 'Morocco', 'https://flagsapi.com/MA/flat/64.png'),
('MZ', 'Mozambique', 'https://flagsapi.com/MZ/flat/64.png'),
('MM', 'Myanmar', 'https://flagsapi.com/MM/flat/64.png'),
('NA', 'Namibia', 'https://flagsapi.com/NA/flat/64.png'),
('NR', 'Nauru', 'https://flagsapi.com/NR/flat/64.png'),
('NP', 'Nepal', 'https://flagsapi.com/NP/flat/64.png'),
('NL', 'Netherlands', 'https://flagsapi.com/NL/flat/64.png'),
('NZ', 'New Zealand', 'https://flagsapi.com/NZ/flat/64.png'),
('NI', 'Nicaragua', 'https://flagsapi.com/NI/flat/64.png'),
('NE', 'Niger', 'https://flagsapi.com/NE/flat/64.png'),
('NG', 'Nigeria', 'https://flagsapi.com/NG/flat/64.png'),
('MK', 'North Macedonia', 'https://flagsapi.com/MK/flat/64.png'),
('NO', 'Norway', 'https://flagsapi.com/NO/flat/64.png'),
('OM', 'Oman', 'https://flagsapi.com/OM/flat/64.png'),
('PK', 'Pakistan', 'https://flagsapi.com/PK/flat/64.png'),
('PW', 'Palau', 'https://flagsapi.com/PW/flat/64.png'),
('PA', 'Panama', 'https://flagsapi.com/PA/flat/64.png'),
('PG', 'Papua New Guinea', 'https://flagsapi.com/PG/flat/64.png'),
('PY', 'Paraguay', 'https://flagsapi.com/PY/flat/64.png'),
('PE', 'Peru', 'https://flagsapi.com/PE/flat/64.png'),
('PH', 'Philippines', 'https://flagsapi.com/PH/flat/64.png'),
('PL', 'Poland', 'https://flagsapi.com/PL/flat/64.png'),
('PT', 'Portugal', 'https://flagsapi.com/PT/flat/64.png'),
('QA', 'Qatar', 'https://flagsapi.com/QA/flat/64.png'),
('RO', 'Romania', 'https://flagsapi.com/RO/flat/64.png'),
('RU', 'Russia', 'https://flagsapi.com/RU/flat/64.png'),
('RW', 'Rwanda', 'https://flagsapi.com/RW/flat/64.png'),
('KN', 'Saint Kitts and Nevis', 'https://flagsapi.com/KN/flat/64.png'),
('LC', 'Saint Lucia', 'https://flagsapi.com/LC/flat/64.png'),
('VC', 'Saint Vincent and the Grenadines', 'https://flagsapi.com/VC/flat/64.png'),
('WS', 'Samoa', 'https://flagsapi.com/WS/flat/64.png'),
('SM', 'San Marino', 'https://flagsapi.com/SM/flat/64.png'),
('ST', 'Sao Tome and Principe', 'https://flagsapi.com/ST/flat/64.png'),
('SA', 'Saudi Arabia', 'https://flagsapi.com/SA/flat/64.png'),
('SN', 'Senegal', 'https://flagsapi.com/SN/flat/64.png'),
('RS', 'Serbia', 'https://flagsapi.com/RS/flat/64.png'),
('SC', 'Seychelles', 'https://flagsapi.com/SC/flat/64.png'),
('SL', 'Sierra Leone', 'https://flagsapi.com/SL/flat/64.png'),
('SG', 'Singapore', 'https://flagsapi.com/SG/flat/64.png'),
('SK', 'Slovakia', 'https://flagsapi.com/SK/flat/64.png'),
('SI', 'Slovenia', 'https://flagsapi.com/SI/flat/64.png'),
('SB', 'Solomon Islands', 'https://flagsapi.com/SB/flat/64.png'),
('SO', 'Somalia', 'https://flagsapi.com/SO/flat/64.png'),
('ZA', 'South Africa', 'https://flagsapi.com/ZA/flat/64.png'),
('SS', 'South Sudan', 'https://flagsapi.com/SS/flat/64.png'),
('ES', 'Spain', 'https://flagsapi.com/ES/flat/64.png'),
('LK', 'Sri Lanka', 'https://flagsapi.com/LK/flat/64.png'),
('SD', 'Sudan', 'https://flagsapi.com/SD/flat/64.png'),
('SR', 'Suriname', 'https://flagsapi.com/SR/flat/64.png'),
('SE', 'Sweden', 'https://flagsapi.com/SE/flat/64.png'),
('CH', 'Switzerland', 'https://flagsapi.com/CH/flat/64.png'),
('SY', 'Syria', 'https://flagsapi.com/SY/flat/64.png'),
('TW', 'Taiwan', 'https://flagsapi.com/TW/flat/64.png'),
('TJ', 'Tajikistan', 'https://flagsapi.com/TJ/flat/64.png'),
('TZ', 'Tanzania', 'https://flagsapi.com/TZ/flat/64.png'),
('TH', 'Thailand', 'https://flagsapi.com/TH/flat/64.png'),
('TL', 'Timor-Leste', 'https://flagsapi.com/TL/flat/64.png'),
('TG', 'Togo', 'https://flagsapi.com/TG/flat/64.png'),
('TO', 'Tonga', 'https://flagsapi.com/TO/flat/64.png'),
('TT', 'Trinidad and Tobago', 'https://flagsapi.com/TT/flat/64.png'),
('TN', 'Tunisia', 'https://flagsapi.com/TN/flat/64.png'),
('TR', 'Turkey', 'https://flagsapi.com/TR/flat/64.png'),
('TM', 'Turkmenistan', 'https://flagsapi.com/TM/flat/64.png'),
('TV', 'Tuvalu', 'https://flagsapi.com/TV/flat/64.png'),
('UG', 'Uganda', 'https://flagsapi.com/UG/flat/64.png'),
('UA', 'Ukraine', 'https://flagsapi.com/UA/flat/64.png'),
('AE', 'United Arab Emirates', 'https://flagsapi.com/AE/flat/64.png'),
('GB', 'United Kingdom', 'https://flagsapi.com/GB/flat/64.png'),
('US', 'United States', 'https://flagsapi.com/US/flat/64.png'),
('UY', 'Uruguay', 'https://flagsapi.com/UY/flat/64.png'),
('UZ', 'Uzbekistan', 'https://flagsapi.com/UZ/flat/64.png'),
('VU', 'Vanuatu', 'https://flagsapi.com/VU/flat/64.png'),
('VE', 'Venezuela', 'https://flagsapi.com/VE/flat/64.png'),
('VN', 'Vietnam', 'https://flagsapi.com/VN/flat/64.png'),
('YE', 'Yemen', 'https://flagsapi.com/YE/flat/64.png'),
('ZM', 'Zambia', 'https://flagsapi.com/ZM/flat/64.png'),
('ZW', 'Zimbabwe', 'https://flagsapi.com/ZW/flat/64.png');
