INSERT INTO product ("sellerId", title, url, description, image_url, image_alt, price, review_score, review_count, order_count) VALUES
(1, 'Flagship Smartphone', 'smartphone-url', 'Experience the latest technology with stunning visuals and speed.', 'image_url_1', 'Smartphone Image', 899.99, 4.5, 100, 500),
(1, 'Gaming Laptop', 'laptop-url', 'High-performance laptop with advanced graphics for gaming and productivity.', 'image_url_2', 'Laptop Image', 1499.99, 4.6, 200, 300),
(2, 'Organic Cotton T-Shirt', 'tshirt-url', 'Soft and breathable t-shirt made from 100% organic cotton.', 'image_url_3', 'T-Shirt Image', 24.99, 4.2, 50, 150),
(2, 'Slim Fit Jeans', 'jeans-url', 'Trendy and comfortable slim-fit jeans for everyday wear.', 'image_url_4', 'Jeans Image', 59.99, 4.3, 70, 100),
(3, 'Premium Cookware Set', 'cookware-url', 'Non-stick and durable cookware set for all your cooking needs.', 'image_url_5', 'Cookware Set Image', 99.99, 4.7, 30, 70),
(3, 'Cordless Vacuum Cleaner', 'vacuum-url', 'Lightweight and powerful cordless vacuum cleaner for easy cleaning.', 'image_url_6', 'Vacuum Cleaner Image', 199.99, 4.5, 60, 80),
(4, 'Eco-Friendly Yoga Mat', 'yoga-mat-url', 'High-quality, eco-friendly yoga mat with excellent grip.', 'image_url_7', 'Yoga Mat Image', 39.99, 4.9, 120, 200),
(4, 'Adjustable Dumbbell Set', 'dumbbells-url', 'Versatile dumbbell set perfect for home workouts.', 'image_url_8', 'Dumbbells Image', 79.99, 4.8, 50, 100),
(5, 'Matte Lipstick', 'lipstick-url', 'Long-lasting matte lipstick with a bold color finish.', 'image_url_9', 'Lipstick Image', 18.99, 4.1, 80, 120),
(5, 'Natural Shampoo', 'shampoo-url', 'Gentle shampoo with natural ingredients for healthy hair.', 'image_url_10', 'Shampoo Image', 9.99, 4.4, 90, 110),
(6, 'RC Sports Car', 'toy-car-url', 'Fast remote control sports car with realistic design.', 'image_url_11', 'Toy Car Image', 34.99, 4.6, 40, 60),
(6, 'Collector Action Figure', 'action-figure-url', 'Detailed superhero action figure for collectors and fans.', 'image_url_12', 'Action Figure Image', 19.99, 4.5, 55, 75),
(7, 'High Gloss Car Wax', 'car-wax-url', 'Premium car wax for a shiny, protective finish.', 'image_url_13', 'Car Wax Image', 14.99, 4.3, 20, 40),
(7, 'Compact Car Vacuum', 'car-vacuum-url', 'Portable and powerful car vacuum cleaner.', 'image_url_14', 'Car Vacuum Image', 49.99, 4.5, 35, 45),
(8, 'Specialty Coffee Beans', 'coffee-url', 'Freshly roasted specialty coffee beans with a rich flavor.', 'image_url_15', 'Coffee Image', 12.99, 4.8, 60, 150),
(8, 'Whole Grain Cereal', 'cereal-url', 'Nutritious whole grain cereal for a healthy breakfast.', 'image_url_16', 'Cereal Image', 5.99, 4.2, 40, 100),
(9, 'Complete Multivitamin', 'multivitamins-url', 'Daily multivitamin with essential nutrients for overall health.', 'image_url_17', 'Multivitamins Image', 24.99, 4.4, 50, 80),
(9, 'Organic Protein Powder', 'protein-powder-url', 'High-quality organic whey protein powder for fitness goals.', 'image_url_18', 'Protein Powder Image', 44.99, 4.7, 45, 90),
(10, 'Award-Winning Novel', 'fiction-book-url', 'A captivating novel from an award-winning author.', 'image_url_19', 'Fiction Book Image', 13.99, 4.9, 100, 180),
(10, 'Inspiring Memoir', 'non-fiction-book-url', 'A best-selling memoir that will inspire and motivate.', 'image_url_20', 'Non-fiction Book Image', 16.99, 4.6, 120, 220),
(1, 'Smartwatch', 'smartwatch-url', 'Stylish and functional smartwatch with fitness tracking features.', 'image_url_21', 'Smartwatch Image', 199.99, 4.4, 150, 220),
(2, 'Bluetooth Headphones', 'headphones-url', 'Wireless headphones with excellent sound quality and noise cancellation.', 'image_url_22', 'Headphones Image', 129.99, 4.5, 180, 240),
(3, 'Electric Kettle', 'electric-kettle-url', 'Sleek and fast electric kettle with temperature control.', 'image_url_23', 'Electric Kettle Image', 49.99, 4.2, 100, 150),
(4, 'Personal Blender', 'blender-url', 'Compact and powerful personal blender for smoothies and shakes.', 'image_url_24', 'Blender Image', 29.99, 4.6, 80, 120),
(5, 'Wireless Mouse', 'mouse-url', 'Ergonomic wireless mouse with precision tracking for productivity.', 'image_url_25', 'Mouse Image', 19.99, 4.3, 200, 270),
(6, 'Kitchen Scale', 'kitchen-scale-url', 'Accurate and easy-to-use digital kitchen scale for cooking.', 'image_url_26', 'Kitchen Scale Image', 15.99, 4.4, 50, 100),
(7, 'Electric Toothbrush', 'electric-toothbrush-url', 'Advanced electric toothbrush with multiple modes for a superior clean.', 'image_url_27', 'Toothbrush Image', 59.99, 4.7, 150, 200),
(8, 'Home Theater System', 'theater-system-url', 'Surround sound home theater system for a cinematic experience.', 'image_url_28', 'Home Theater Image', 499.99, 4.8, 80, 150),
(9, 'Portable Power Bank', 'power-bank-url', 'High-capacity portable power bank for charging on the go.', 'image_url_29', 'Power Bank Image', 29.99, 4.5, 120, 160),
(10, 'Gaming Mouse', 'gaming-mouse-url', 'Precision gaming mouse with customizable buttons and RGB lighting.', 'image_url_30', 'Gaming Mouse Image', 49.99, 4.6, 90, 140),
(11, 'Smart Home Hub', 'home-hub-url', 'Central hub to control your smart home devices.', 'image_url_31', 'Smart Home Hub Image', 89.99, 4.7, 60, 100),
(12, 'Electric Grill', 'electric-grill-url', 'Compact and powerful electric grill for indoor cooking.', 'image_url_32', 'Electric Grill Image', 79.99, 4.4, 110, 180),
(13, 'Touchscreen Monitor', 'touchscreen-monitor-url', 'High-definition touchscreen monitor with multiple connectivity options.', 'image_url_33', 'Monitor Image', 219.99, 4.5, 150, 220),
(14, 'UV Sterilizer Box', 'sterilizer-box-url', 'Compact UV sterilizer box for disinfecting your phone and accessories.', 'image_url_34', 'Sterilizer Box Image', 39.99, 4.6, 75, 120),
(15, 'Smart Light Bulbs', 'smart-light-bulbs-url', 'Energy-efficient smart light bulbs with adjustable color temperature.', 'image_url_35', 'Smart Light Bulb Image', 24.99, 4.4, 200, 280),
(16, 'Electric Blanket', 'electric-blanket-url', 'Cozy electric blanket with adjustable heat settings for ultimate comfort.', 'image_url_36', 'Electric Blanket Image', 69.99, 4.8, 120, 160),
(17, 'Smart Thermostat', 'smart-thermostat-url', 'Programmable smart thermostat to optimize home heating and cooling.', 'image_url_37', 'Smart Thermostat Image', 129.99, 4.7, 150, 210),
(18, 'Cordless Hair Dryer', 'hair-dryer-url', 'Lightweight and powerful cordless hair dryer for styling on the go.', 'image_url_38', 'Hair Dryer Image', 99.99, 4.5, 110, 140),
(19, 'Pet Camera', 'pet-camera-url', 'Monitor your pets with this high-definition pet camera with two-way audio.', 'image_url_39', 'Pet Camera Image', 79.99, 4.4, 80, 120),
(20, 'Digital Camera', 'digital-camera-url', 'Compact digital camera with high-quality photo and video capture.', 'image_url_40', 'Digital Camera Image', 249.99, 4.6, 100, 170),
(1, 'Robot Vacuum Cleaner', 'robot-vacuum-url', 'Smart robot vacuum with automatic cleaning and scheduling.', 'image_url_41', 'Robot Vacuum Image', 299.99, 4.5, 180, 250),
(2, 'Wireless Charger', 'wireless-charger-url', 'Fast and efficient wireless charger for smartphones and devices.', 'image_url_42', 'Wireless Charger Image', 39.99, 4.3, 150, 220),
(3, 'Smart Thermometer', 'smart-thermometer-url', 'Smart thermometer with app control and temperature tracking.', 'image_url_43', 'Smart Thermometer Image', 49.99, 4.4, 100, 140),
(4, 'Electric Pressure Cooker', 'pressure-cooker-url', 'Fast and efficient electric pressure cooker for delicious meals.', 'image_url_44', 'Pressure Cooker Image', 89.99, 4.6, 80, 130),
(5, 'Game Console', 'game-console-url', 'Next-gen gaming console with stunning graphics and exclusive titles.', 'image_url_45', 'Game Console Image', 499.99, 4.7, 200, 350),
(6, 'Digital Drawing Tablet', 'drawing-tablet-url', 'Precision digital drawing tablet for graphic designers and artists.', 'image_url_46', 'Drawing Tablet Image', 129.99, 4.6, 90, 150),
(7, 'Electric Juicer', 'electric-juicer-url', 'Powerful electric juicer for fresh and healthy juices.', 'image_url_47', 'Electric Juicer Image', 59.99, 4.5, 110, 170),
(8, 'Smart Fitness Tracker', 'fitness-tracker-url', 'Wearable fitness tracker to monitor health and activity levels.', 'image_url_48', 'Fitness Tracker Image', 69.99, 4.3, 140, 210),
(9, 'Cordless Drill', 'cordless-drill-url', 'High-performance cordless drill for home improvement projects.', 'image_url_49', 'Cordless Drill Image', 79.99, 4.5, 90, 140),
(10, 'Fitness Resistance Bands', 'resistance-bands-url', 'Set of durable resistance bands for strength training and rehabilitation.', 'image_url_50', 'Resistance Bands Image', 19.99, 4.4, 180, 240),
(11, 'Portable Projector', 'portable-projector-url', 'Compact and portable projector for movies and presentations.', 'image_url_51', 'Portable Projector Image', 199.99, 4.6, 75, 120),
(12, 'Bluetooth Speaker', 'bluetooth-speaker-url', 'Waterproof Bluetooth speaker with powerful sound and deep bass.', 'image_url_52', 'Bluetooth Speaker Image', 59.99, 4.5, 160, 230),
(13, 'Smart Lock', 'smart-lock-url', 'Secure smart lock with remote access and keyless entry for doors.', 'image_url_53', 'Smart Lock Image', 119.99, 4.8, 100, 160),
(14, 'Electric Massage Gun', 'massage-gun-url', 'Portable electric massage gun for muscle relaxation and recovery.', 'image_url_54', 'Massage Gun Image', 129.99, 4.6, 90, 140),
(15, 'Digital Photo Frame', 'photo-frame-url', 'Wi-Fi-enabled digital photo frame to display your favorite memories.', 'image_url_55', 'Photo Frame Image', 89.99, 4.4, 80, 120),
(16, 'Coffee Maker', 'coffee-maker-url', 'High-quality coffee maker with programmable brewing options.', 'image_url_56', 'Coffee Maker Image', 69.99, 4.3, 150, 200),
(17, 'Stand Mixer', 'stand-mixer-url', 'Heavy-duty stand mixer with multiple attachments for baking and cooking.', 'image_url_57', 'Stand Mixer Image', 249.99, 4.7, 130, 180),
(18, 'Smart Plug', 'smart-plug-url', 'Energy-efficient smart plug to control devices remotely with your phone.', 'image_url_58', 'Smart Plug Image', 24.99, 4.5, 200, 280),
(19, 'Air Purifier', 'air-purifier-url', 'Portable air purifier to eliminate dust, pollen, and odors for clean air.', 'image_url_59', 'Air Purifier Image', 149.99, 4.6, 110, 160),
(20, 'Robot Pet Toy', 'robot-pet-toy-url', 'Interactive robot pet toy with motion sensors and sound effects.', 'image_url_60', 'Robot Pet Toy Image', 39.99, 4.4, 60, 100),
(1, 'Wireless Earbuds', 'wireless-earbuds-url', 'Compact and comfortable wireless earbuds with noise cancellation.', 'image_url_61', 'Wireless Earbuds Image', 79.99, 4.6, 220, 300),
(2, 'Electric Toothbrush', 'electric-toothbrush-url', 'Sonic electric toothbrush for effective and gentle cleaning.', 'image_url_62', 'Electric Toothbrush Image', 59.99, 4.7, 190, 250),
(3, 'Smart Wi-Fi Camera', 'wifi-camera-url', 'HD smart Wi-Fi security camera with motion detection and remote viewing.', 'image_url_63', 'Wi-Fi Camera Image', 129.99, 4.8, 150, 210),
(4, 'Gaming Headset', 'gaming-headset-url', 'High-quality gaming headset with surround sound and a built-in mic.', 'image_url_64', 'Gaming Headset Image', 99.99, 4.6, 220, 280),
(5, 'Electric Kettle', 'electric-kettle-url', 'Fast boiling electric kettle with temperature control settings.', 'image_url_65', 'Electric Kettle Image', 49.99, 4.5, 180, 240),
(6, 'Instant Camera', 'instant-camera-url', 'Retro-style instant camera for instant print photos and fun memories.', 'image_url_66', 'Instant Camera Image', 79.99, 4.4, 200, 270),
(7, 'Portable Air Conditioner', 'portable-ac-url', 'Compact portable air conditioner for cooling rooms and offices.', 'image_url_67', 'Portable AC Image', 399.99, 4.5, 110, 180),
(8, 'Bluetooth Keyboard', 'bluetooth-keyboard-url', 'Ergonomic wireless Bluetooth keyboard with quiet keys and long battery life.', 'image_url_68', 'Bluetooth Keyboard Image', 59.99, 4.7, 230, 310),
(9, 'Smart Light Bulbs', 'smart-light-bulbs-url', 'Set of smart bulbs for customizable lighting control via smartphone.', 'image_url_69', 'Smart Light Bulbs Image', 29.99, 4.6, 190, 270),
(10, 'Electric Grill', 'electric-grill-url', 'Indoor electric grill for grilling meats and vegetables with ease.', 'image_url_70', 'Electric Grill Image', 149.99, 4.5, 120, 180),
(11, 'Cordless Hedge Trimmer', 'hedge-trimmer-url', 'Lightweight and powerful cordless hedge trimmer for garden maintenance.', 'image_url_71', 'Hedge Trimmer Image', 89.99, 4.4, 90, 130),
(12, 'Smart Home Hub', 'home-hub-url', 'Central hub for controlling all your smart devices through one app.', 'image_url_72', 'Smart Home Hub Image', 99.99, 4.7, 140, 200),
(13, 'Electric Skateboard', 'electric-skateboard-url', 'High-speed electric skateboard with long-lasting battery and smooth ride.', 'image_url_73', 'Electric Skateboard Image', 299.99, 4.8, 50, 100),
(14, 'Solar Power Bank', 'solar-power-bank-url', 'Portable solar-powered charger for phones and devices on the go.', 'image_url_74', 'Solar Power Bank Image', 39.99, 4.3, 160, 220),
(15, 'Smart Watch Strap', 'smartwatch-strap-url', 'Customizable smartwatch straps to fit various styles and comfort.', 'image_url_75', 'Smartwatch Strap Image', 19.99, 4.5, 80, 120),
(16, 'Electric Wine Opener', 'wine-opener-url', 'Electric wine opener with easy one-touch operation for effortless bottle opening.', 'image_url_76', 'Wine Opener Image', 39.99, 4.6, 140, 190),
(17, 'Air Fryer', 'air-fryer-url', 'Health-conscious air fryer for quick and crispy cooking without oil.', 'image_url_77', 'Air Fryer Image', 129.99, 4.7, 220, 300),
(18, 'Smart Mirror', 'smart-mirror-url', 'Mirror with built-in LED lights and Bluetooth speaker for daily routines.', 'image_url_78', 'Smart Mirror Image', 159.99, 4.8, 70, 100),
(19, 'Electric Bike', 'electric-bike-url', 'Eco-friendly electric bike with a powerful motor and long battery life.', 'image_url_79', 'Electric Bike Image', 799.99, 4.7, 90, 150),
(20, 'Home Security System', 'security-system-url', 'Comprehensive home security system with cameras and sensors for full coverage.', 'image_url_80', 'Security System Image', 499.99, 4.9, 80, 120),
(1, 'Portable Power Station', 'portable-power-station-url', 'Rechargeable portable power station for outdoor adventures and emergencies.', 'image_url_81', 'Power Station Image', 299.99, 4.7, 100, 150),
(2, 'VR Headset', 'vr-headset-url', 'Virtual reality headset for immersive gaming and experiences.', 'image_url_82', 'VR Headset Image', 249.99, 4.8, 130, 180),
(3, 'Robot Vacuum Cleaner', 'robot-vacuum-url', 'Smart robot vacuum with powerful suction and self-charging capabilities.', 'image_url_83', 'Robot Vacuum Image', 199.99, 4.6, 220, 300),
(4, 'Smart Thermostat', 'smart-thermostat-url', 'Wi-Fi enabled smart thermostat for efficient energy management and remote control.', 'image_url_84', 'Smart Thermostat Image', 129.99, 4.5, 180, 250),
(5, 'Fitness Tracker', 'fitness-tracker-url', 'Advanced fitness tracker to monitor your health and workout progress.', 'image_url_85', 'Fitness Tracker Image', 59.99, 4.4, 170, 240),
(6, 'Wireless Charger', 'wireless-charger-url', 'Qi-enabled wireless charger for fast and convenient phone charging.', 'image_url_86', 'Wireless Charger Image', 39.99, 4.3, 210, 280),
(7, 'Gaming Laptop Backpack', 'gaming-laptop-backpack-url', 'Durable and spacious backpack designed for gaming laptops and accessories.', 'image_url_87', 'Laptop Backpack Image', 69.99, 4.6, 90, 120),
(8, 'Smartphone Gimbal', 'smartphone-gimbal-url', 'Stabilizing gimbal for smooth video recording with your smartphone.', 'image_url_88', 'Smartphone Gimbal Image', 119.99, 4.5, 80, 110),
(9, 'Over-Ear Headphones', 'over-ear-headphones-url', 'Noise-canceling over-ear headphones with superior sound quality.', 'image_url_89', 'Over-Ear Headphones Image', 149.99, 4.7, 250, 350),
(10, 'Waterproof Bluetooth Speaker', 'bluetooth-speaker-url', 'Durable and waterproof Bluetooth speaker for outdoor use and parties.', 'image_url_90', 'Bluetooth Speaker Image', 49.99, 4.6, 190, 260),
(11, 'Drone with Camera', 'drone-camera-url', 'High-definition drone with camera for aerial photography and video capture.', 'image_url_91', 'Drone Image', 299.99, 4.8, 100, 140),
(12, 'Electric Scooter', 'electric-scooter-url', 'Eco-friendly electric scooter with a fast, smooth ride and long battery life.', 'image_url_92', 'Electric Scooter Image', 399.99, 4.7, 120, 160),
(13, 'Pet Camera', 'pet-camera-url', 'Camera to monitor and interact with your pets remotely via smartphone.', 'image_url_93', 'Pet Camera Image', 99.99, 4.5, 140, 180),
(14, 'Smart Water Bottle', 'smart-water-bottle-url', 'Smart water bottle that tracks your hydration and reminds you to drink.', 'image_url_94', 'Smart Water Bottle Image', 39.99, 4.4, 110, 150),
(15, 'Gaming Mouse', 'gaming-mouse-url', 'Precision gaming mouse with customizable buttons and ergonomic design.', 'image_url_95', 'Gaming Mouse Image', 49.99, 4.6, 160, 220),
(16, 'Smart Plugs', 'smart-plugs-url', 'Set of smart plugs for controlling home appliances remotely through an app.', 'image_url_96', 'Smart Plugs Image', 29.99, 4.5, 200, 270),
(17, 'Outdoor Projector', 'outdoor-projector-url', 'Portable outdoor projector for backyard movie nights and presentations.', 'image_url_97', 'Outdoor Projector Image', 249.99, 4.7, 90, 130),
(18, 'Portable Bluetooth Keyboard', 'portable-bluetooth-keyboard-url', 'Compact Bluetooth keyboard for on-the-go typing and productivity.', 'image_url_98', 'Portable Bluetooth Keyboard Image', 39.99, 4.4, 160, 220),
(19, 'Electric Massage Gun', 'massage-gun-url', 'Handheld electric massage gun for muscle relief and relaxation.', 'image_url_99', 'Massage Gun Image', 129.99, 4.8, 140, 190),
(20, 'Smart Ring', 'smart-ring-url', 'Stylish and functional smart ring for tracking fitness and notifications.', 'image_url_100', 'Smart Ring Image', 79.99, 4.6, 110, 150);
