INSERT INTO product ("sellerId", title, url, description, image_url, image_alt, price, "currencyId", review_score, review_count, order_count) VALUES
(1, 'Flagship Smartphone', 'smartphone-url', 'Experience the latest technology with stunning visuals and speed.', 'image_url_1', 'Smartphone Image', 899.99, 1, 4.5, 100, 500),
(1, 'Gaming Laptop', 'laptop-url', 'High-performance laptop with advanced graphics for gaming and productivity.', 'image_url_2', 'Laptop Image', 1499.99, 1, 4.6, 200, 300),
(2, 'Organic Cotton T-Shirt', 'tshirt-url', 'Soft and breathable t-shirt made from 100% organic cotton.', 'image_url_3', 'T-Shirt Image', 24.99, 1, 4.2, 50, 150),
(2, 'Slim Fit Jeans', 'jeans-url', 'Trendy and comfortable slim-fit jeans for everyday wear.', 'image_url_4', 'Jeans Image', 59.99, 1, 4.3, 70, 100),
(3, 'Premium Cookware Set', 'cookware-url', 'Non-stick and durable cookware set for all your cooking needs.', 'image_url_5', 'Cookware Set Image', 99.99, 1, 4.7, 30, 70),
(3, 'Cordless Vacuum Cleaner', 'vacuum-url', 'Lightweight and powerful cordless vacuum cleaner for easy cleaning.', 'image_url_6', 'Vacuum Cleaner Image', 199.99, 1, 4.5, 60, 80),
(4, 'Eco-Friendly Yoga Mat', 'yoga-mat-url', 'High-quality, eco-friendly yoga mat with excellent grip.', 'image_url_7', 'Yoga Mat Image', 39.99, 1, 4.9, 120, 200),
(4, 'Adjustable Dumbbell Set', 'dumbbells-url', 'Versatile dumbbell set perfect for home workouts.', 'image_url_8', 'Dumbbells Image', 79.99, 1, 4.8, 50, 100),
(5, 'Matte Lipstick', 'lipstick-url', 'Long-lasting matte lipstick with a bold color finish.', 'image_url_9', 'Lipstick Image', 18.99, 1, 4.1, 80, 120),
(5, 'Natural Shampoo', 'shampoo-url', 'Gentle shampoo with natural ingredients for healthy hair.', 'image_url_10', 'Shampoo Image', 9.99, 1, 4.4, 90, 110),
(6, 'RC Sports Car', 'toy-car-url', 'Fast remote control sports car with realistic design.', 'image_url_11', 'Toy Car Image', 34.99, 1, 4.6, 40, 60),
(6, 'Collector Action Figure', 'action-figure-url', 'Detailed superhero action figure for collectors and fans.', 'image_url_12', 'Action Figure Image', 19.99, 1, 4.5, 55, 75),
(7, 'High Gloss Car Wax', 'car-wax-url', 'Premium car wax for a shiny, protective finish.', 'image_url_13', 'Car Wax Image', 14.99, 1, 4.3, 20, 40),
(7, 'Compact Car Vacuum', 'car-vacuum-url', 'Portable and powerful car vacuum cleaner.', 'image_url_14', 'Car Vacuum Image', 49.99, 1, 4.5, 35, 45),
(8, 'Specialty Coffee Beans', 'coffee-url', 'Freshly roasted specialty coffee beans with a rich flavor.', 'image_url_15', 'Coffee Image', 12.99, 1, 4.8, 60, 150),
(8, 'Whole Grain Cereal', 'cereal-url', 'Nutritious whole grain cereal for a healthy breakfast.', 'image_url_16', 'Cereal Image', 5.99, 1, 4.2, 40, 100),
(9, 'Complete Multivitamin', 'multivitamins-url', 'Daily multivitamin with essential nutrients for overall health.', 'image_url_17', 'Multivitamins Image', 24.99, 1, 4.4, 50, 80),
(9, 'Organic Protein Powder', 'protein-powder-url', 'High-quality organic whey protein powder for fitness goals.', 'image_url_18', 'Protein Powder Image', 44.99, 1, 4.7, 45, 90),
(10, 'Award-Winning Novel', 'fiction-book-url', 'A captivating novel from an award-winning author.', 'image_url_19', 'Fiction Book Image', 13.99, 1, 4.9, 100, 180),
(10, 'Inspiring Memoir', 'non-fiction-book-url', 'A best-selling memoir that will inspire and motivate.', 'image_url_20', 'Non-fiction Book Image', 16.99, 1, 4.6, 120, 220);
