INSERT INTO Review ("productId", score, title, content, image_urls, "usrId")
VALUES
(1, 5, 'Excellent Smartphone', 'This smartphone has an amazing camera and great battery life!', '', 1),
(1, 4, 'Good Value', 'Pretty good performance for the price. Happy with my purchase.', '', 2),
(2, 5, 'Awesome Laptop', 'This laptop handles gaming and work with ease. Highly recommend!', '', 3),
(2, 3, 'Decent Laptop', 'It’s okay, but could be faster for gaming.', '', 4),
(3, 4, 'Beautiful Dining Table', 'Looks great in my dining room, very sturdy!', '', 5),
(3, 5, 'Perfect for Family Meals', 'This table fits our family perfectly and is of high quality.', '', 6),
(4, 4, 'Great Coffee Maker', 'Brews a delicious cup of coffee every time!', '', 7),
(4, 5, 'Must-Have Kitchen Gadget', 'I can’t live without my coffee maker now.', '', 8),
(5, 5, 'Incredible Sound Quality', 'These headphones are amazing for music lovers!', '', 9),
(5, 4, 'Comfortable and Stylish', 'Very comfortable for long hours of use.', '', 10),
(6, 5, 'Fantastic Smartwatch', 'Tracks my workouts perfectly and looks great!', '', 11),
(6, 4, 'Helpful Fitness Tracker', 'Great for keeping track of my fitness goals.', '', 12),
(7, 3, 'Good Backpack', 'Spacious but not very durable.', '', 13),
(7, 4, 'Nice Design', 'Stylish backpack for everyday use.', '', 14),
(8, 5, 'Great Running Shoes', 'These shoes are super comfortable for running!', '', 15),
(8, 4, 'Perfect Fit', 'Fit like a glove and look good too!', '', 16),
(9, 4, 'Amazing Read', 'A thrilling story that kept me hooked!', '', 17),
(9, 5, 'Best Book of the Year', 'Loved every page of this book!', '', 18),
(10, 5, 'Awesome Mountain Bike', 'This bike handles trails like a pro!', '', 19),
(10, 4, 'Good Performance', 'Great for off-road adventures.', '', 20),
(11, 5, 'Stunning DSLR', 'Takes amazing pictures, highly recommend!', '', 1),
(11, 4, 'Great for Beginners', 'Perfect camera for someone just starting out.', '', 2),
(12, 5, 'Best Smart TV', 'Crystal clear picture and fantastic sound!', '', 3),
(12, 4, 'Great for Movie Nights', 'Perfect for binge-watching my favorite shows.', '', 4),
(13, 5, 'Epic Gaming Console', 'The graphics are stunning, best console ever!', '', 5),
(13, 4, 'Fun Games', 'Great selection of games available.', '', 6),
(14, 4, 'Stylish Coffee Table', 'Looks great in my living room!', '', 7),
(14, 5, 'Functional and Chic', 'Very pleased with the quality and design.', '', 8),
(15, 5, 'Amazing Smart Thermostat', 'Saves me money on energy bills!', '', 9),
(15, 4, 'Very Convenient', 'Easy to control from my phone.', '', 10),
(16, 5, 'Fantastic Drone', 'Takes amazing aerial shots!', '', 11),
(16, 4, 'Fun to Fly', 'Great for outdoor adventures.', '', 12),
(17, 4, 'Good Electric Kettle', 'Boils water quickly and efficiently.', '', 13),
(17, 5, 'Must-Have Kitchen Appliance', 'Perfect for tea lovers!', '', 14),
(18, 4, 'Great Air Fryer', 'Healthy cooking made easy.', '', 15),
(18, 5, 'Best Kitchen Gadget', 'I use this every day!', '', 16),
(19, 5, 'Excellent Sound Quality', 'This speaker is amazing for parties!', '', 17),
(19, 4, 'Portable and Easy to Use', 'Great for taking on the go.', '', 18),
(20, 5, 'Wonderful E-Reader', 'Perfect for reading anywhere, love the screen!', '', 19),
(20, 4, 'Great Battery Life', 'Lasts for weeks on a single charge!', '', 20);
