INSERT INTO Review ("productId", score, title, content, image_urls, "usrId") VALUES
(1, 5, 'Exceptional Quality Product, Highly Recommended!', 'Absolutely love this smartphone! The camera quality is beyond what I expected, and battery life easily lasts over a day with heavy use. Couldn''t be happier.', '', 1),
(1, 4, 'Decent, but pricey', 'Good performance overall. Could use a better screen in bright light conditions.', '', 2),
(2, 1, 'Worst Experience Ever!!!', 'The laptop stopped working within two weeks. Customer support was unhelpful, and I regret this purchase.', '', 3),
(2, 5, 'Fantastic Performance', 'Runs all my games smoothly, super happy!', '', 4),
(3, 4, 'Elegant and Durable', 'The dining table has a beautiful finish and holds up well with daily use. Easy to clean.', '', 5),
(3, 5, 'Perfect for gatherings!', 'My family loves it, comfortably seats 6 people.', '', 6),
(4, 5, 'A Game Changer for Coffee Lovers!!!', 'I use this coffee maker every morning, and it brews the perfect cup of coffee in minutes. Can’t imagine my mornings without it now!', '', 7),
(4, 1, 'Terrible Product', 'Stopped working after a week. Very disappointed!', '', 8),
(5, 5, 'Best Headphones I''ve Ever Used', 'The sound quality is unparalleled. Highly recommend for audiophiles.', '', 9),
(5, 3, 'Not Very Comfortable', 'The sound is good, but they hurt my ears after prolonged use.', '', 10),
(6, 4, 'Great Watch for Daily Use', 'Tracks everything I need and has an amazing battery life. Looks stylish too!', '', 11),
(6, 2, 'Limited Features', 'Misses some essential fitness tracking features. Expected more for the price.', '', 12),
(7, 3, 'Durable, but bulky', 'It''s a bit larger than expected but holds up well.', '', 13),
(7, 5, 'Stylish and Comfortable', 'Perfect backpack for school or travel!', '', 14),
(8, 5, 'Amazing Comfort and Fit', 'Perfect running shoes! My feet feel great after long runs.', '', 15),
(8, 4, 'Good Shoes', 'Fits well, though they wore out faster than expected.', '', 16),
(9, 5, 'Best Book I''ve Read This Year!', 'Couldn''t put it down. Highly recommended for thriller fans!', '', 17),
(9, 2, 'Overrated', 'Didn’t live up to the hype for me. Found it dull.', '', 18),
(10, 5, 'Unbelievable Mountain Bike!', 'I love taking this bike on trails! Solid build and smooth rides.', '', 19),
(10, 3, 'Just Okay', 'Works fine but doesn''t handle rough trails well.', '', 20),
(11, 5, 'Professional Quality DSLR', 'Produces incredible images, great for any level of photographer.', '', 1),
(11, 4, 'Good Starter Camera', 'Simple to use and has decent picture quality.', '', 2),
(12, 5, 'Best TV for the Price', 'Amazing picture quality and easy to set up. Highly satisfied!', '', 3),
(12, 3, 'Average TV', 'Not bad, but not impressive. Gets the job done.', '', 4),
(13, 5, 'Must-Have Gaming Console!', 'Hours of fun and stunning visuals. Worth every penny!', '', 5),
(13, 4, 'Great Games Available', 'Fun and easy to use. Would love more exclusive games.', '', 6),
(14, 4, 'Nice Coffee Table', 'Great for small spaces and looks nice in the living room.', '', 7),
(14, 5, 'Beautiful Piece', 'Matches my decor perfectly, and it’s very functional.', '', 8),
(15, 5, 'A Real Energy Saver!', 'This thermostat has saved me money on heating. So easy to control!', '', 9),
(15, 3, 'Not As Convenient As Expected', 'Some connectivity issues, but it’s still decent.', '', 10),
(16, 5, 'The Best Drone for the Price', 'Easy to fly and takes great photos. Perfect for beginners.', '', 11),
(16, 4, 'Good for Casual Use', 'Works well, though some of the controls are finicky.', '', 12),
(17, 4, 'Efficient and Compact', 'Heats up fast and looks good on the counter.', '', 13),
(17, 5, 'Best Kettle for Daily Use', 'I use this every day! Boils quickly and quietly.', '', 14),
(18, 4, 'Very Useful Air Fryer', 'Helps me eat healthier. Cooks food evenly.', '', 15),
(18, 5, 'Best Kitchen Appliance I Own', 'I cook everything in this air fryer now!', '', 16),
(19, 5, 'Party Must-Have!', 'This speaker has excellent bass and volume. Perfect for gatherings!', '', 17),
(19, 3, 'Not Great for Outdoors', 'Doesn’t get loud enough in open spaces.', '', 18),
(20, 5, 'Perfect for Book Lovers', 'The e-ink screen is easy on the eyes. Battery lasts forever!', '', 19),
(20, 4, 'Decent E-Reader', 'Works well, though the screen could be brighter.', '', 20);
