-- Truncate all tables and reset the ID sequences
TRUNCATE TABLE "Country" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Currency" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "User" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Category" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Product" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Address" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Order" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Basket" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "OrderItem" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BasketItem" RESTART IDENTITY CASCADE;
