"use client";
// import type { Metadata, Viewport } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
import { Provider } from "@/contexts";
import NavBar from "@/components/navigation";
import { SessionProvider } from "next-auth/react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

// export const viewport: Viewport = {
//   width: "device-width",
//   initialScale: 1
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: JSX.Element;
}>) {

  return (
    <html lang="en" style={{ margin: 0, padding: 0, boxSizing: "border-box"}}>
      <body style={{ minWidth: "320px" }}>
        <SessionProvider>
          <Provider>
              <div style={{ gridColumn: "1/-1"}}>
                <NavBar />
                {children}
              </div>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
